### ISSUE TITLE
Error building interaction model > Dialog Model

### ISSUE THREAD

**Issue by julesmoretti** [alexa/alexa-cookbook#35]
I am getting the following error on build:

```
When using a Dialog Model, sample utterances for intents cannot contain only slots
```

Any advice on how to determine what is causing this error?

**Comment by Meenakshi14** [comment]
while using dialog model, you can't use single slots as utterance.  You will need to remove utterances that contain only one slot as phrase like {toCity}, {fromCity} and {travelDate}

**Comment by julesmoretti** [comment]
@meenakshi14 thank you.

Similar errors occurs when using slots within strings.

What is really confusing is that this practice was based on the mytrip skill from the amazon tutorials.

Not sure how they got it working without those errors.

**Comment by SleepyDeveloper** [comment]
@julesmoretti Sorry for the confusion. Things are constantly changing. I will update the InteractionModel.json so it will build.

**Comment by SleepyDeveloper** [comment]
@julesmoretti This has been fixed.

**Comment by sambithota** [comment]
I still see this issue while building Dialog Model. Is this fixed or a problem with Beta?

**Comment by bmontgom** [comment]
I'm with Sambithota. Has this been fixed or is this a problem with the beta?

**Comment by sambithota** [comment]
@bmontgom. I had to create a whole new skill to get over this issue. It seemed to work for a new skill. Seems like an issue in beta

**Comment by SleepyDeveloper** [comment]
@julesmoretti regarding slot only utterances, they are not allowed at the top level utterance in Dialog Management, however you can have a slot only utterance at the slot utterance level. 

If you click on the toCity slot and in the utterances box type {toCity} it will build successfully.

**Comment by praveenmenon** [comment]
Is this issue fixed. I am facing the the same issue when creating an utterance with just on slot value. It was working fine but now i am getting this error. “Sample intent utterances with phrase types cannot consist of only slots.” It was working fine before and it works fine on another skill.
